controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
  #  schemes: [https]

home:
    path: /
    controller: App\Controller\HomeController::index

cgv:
    path: /cgv
    controller: App\Controller\HomeController::cgv
